server:
  port: 8081
security:
  tokenurl: http://localhost:8080/oauth/check_token
  clientid: client
  clientsecret: client123
management:
  server:
    port: 9001
spring:
  main:
    allow-bean-definition-overriding: true